version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3001:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0", "--reload"]

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
